import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/mycomponents/Header";
import Footer from "@/mycomponents/Footer";

import "./mylayout.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SimpleNotes",
  description: "Generated by Ruslan Zeynalov",
    icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">


        <header>
          <Header />
        </header>
        
        <div className="main-content" >
          {children}
        </div>

        <footer>
          <Footer />
        </footer>


      </body>
    </html>
  );
}
